name: Deploy RabbitConsumer1

on:
  push:
    branches: [ main ]
    paths:
      - 'RabbitConsumer1/**' # Triggers ONLY when something in this folder changes

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./RabbitConsumer1
        file: ./RabbitConsumer1/Dockerfile # Points directly to this consumer's Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/rabbit-consumer-1:latest
