name: Deploy RabbitConsumer2

on:
  push:
    branches: [main]
    paths:
      - "RabbitConsumer2/**"

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Verify Dockerfile Presence
        run: |
          if [ ! -f "./RabbitConsumer2/Dockerfile" ]; then
            echo "Error: Dockerfile not found in RabbitConsumer2 directory!"
            exit 1
          fi

      - name: Build Local Container
        run: |
          docker build -t rabbit-consumer-2:local ./RabbitConsumer2/

      - name: Workflow Status Output
        run: echo "Successfully built and verified RabbitConsumer2 container!"
